// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcmdeezoexxbxzyipsil.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjbWRlZXpvZXh4Ynh6eWlwc2lsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MTM4ODIsImV4cCI6MjA3MjE4OTg4Mn0.FtuIg0Nkq2L5F_mPlQ4g7jvUapSAy-VoO_KW0Mc_3iY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});